# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "git@github.com:#{repo}.git" }

gem 'byebug', group: [:development, :test]
gem 'derivative_rodeo', path: './derivative_rodeo'
gem 'dotenv'
gem 'httparty'
gem 'nokogiri'
gem 'pry', group: [:test]
gem 'rake', group: [:development]
gem 'rspec', '~> 3.0', groups: [:development, :test]
gem 'rubyzip'
