# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: space-stone
# app and org for use with dashboard.serverless.com
app: space-stone-aws
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: ruby2.7

# you can overwrite defaults here
  stage: ${opt:stage, 'dev'}
  region: ${opt:aws_region, 'us-west-2'}

# you can add statements to the Lambda function's IAM Role here
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "sqs:*"
          Resource: "*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.rb'
#    - '!exclude-me-dir/**'
#    - include-me.rb
#    - include-me-dir/**

functions:
  process_csv:
    handler: handler.process_csv
    events:
      - httpApi:
        path: /csv/create
        method: POST

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"


constructs:
  download:
    type: queue
    maxRetries: 2
    batchSize: 5
    worker:
      handler: handler.download
      memorySize: 512 # optional, in MB, default is 1024
      timeout: 900 # optional, in seconds, default is 6
      ephemeralStorageSize: 10240
      environment:
        RUBYOPT: '-W0'
        OCR_QUEUE_URL: ${construct:ocr.queueUrl}
        THUMBNAIL_QUEUE_URL: ${construct:thumbnail.queueUrl}
  ocr:
    type: queue
    maxRetries: 2
    batchSize: 5
    worker:
      handler: handler.ocr
      memorySize: 512 # optional, in MB, default is 1024
      timeout: 900 # optional, in seconds, default is 6
      ephemeralStorageSize: 2560
      environment:
        RUBYOPT: '-W0'
  thumbnail:
    type: queue
    maxRetries: 2
    batchSize: 1
    worker:
      handler: handler.thumbnail
      memorySize: 4096 # optional, in MB, default is 1024
      timeout: 900 # optional, in seconds, default is 6
      ephemeralStorageSize: 2560
      environment:
        RUBYOPT: '-W0'
        OCR_QUEUE_URL: ${construct:ocr.queueUrl}

plugins:
  - serverless-lift
  - ./../serverless-ruby-layer
  - serverless-ignore
custom:
  rubyLayer:
    include_functions:
      - ocrWorker
      - thumbnailWorker
    use_docker: true
    docker_file: Dockerfile
    native_libs:
      - /opt
