# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: space-stone
# app and org for use with dashboard.serverless.com
app: space-stone-aws
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: ruby2.7

# you can overwrite defaults here
  stage: ${opt:stage, 'dev'}
  region: ${opt:aws_region, 'us-west-2'}

# you can add statements to the Lambda function's IAM Role here
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "sqs:*"
          Resource: "*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.rb'
#    - '!exclude-me-dir/**'
#    - include-me.rb
#    - include-me-dir/**

functions:
  copy:
    handler: handler.copy
    events: # All events associated with this function
      - httpApi: 'POST /copy'
    environment:
      RUBYOPT: '-W0'

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"


constructs:
  preprocessed:
    type: storage

  split-ocr-thumbnail:
    type: queue
    maxRetries: 2
    batchSize: 5
    worker:
      handler: handler.split_ocr_thumbnail
      memorySize: 512 # optional, in MB, default is 1024
      timeout: 900 # optional, in seconds, default is 6
      ephemeralStorageSize: 10240
      environment:
        RUBYOPT: '-W0'
        OCR_QUEUE_URL: ${construct:ocr.queueUrl}
        THUMBNAIL_QUEUE_URL: ${construct:thumbnail.queueUrl}
        S3_BUCKET_NAME: ${construct:preprocessed.bucketName}
  ocr:
    type: queue
    maxRetries: 2
    batchSize: 5
    worker:
      handler: handler.ocr
      memorySize: 512 # optional, in MB, default is 1024
      timeout: 900 # optional, in seconds, default is 6
      ephemeralStorageSize: 2560
      environment:
        RUBYOPT: '-W0'
        S3_BUCKET_NAME: ${construct:preprocessed.bucketName}
        WORD_COORDINATES_QUEUE_URL: ${construct:word-coordinates.queueUrl}
        PLAIN_TEXT_QUEUE_URL: ${construct:plain-text.queueUrl}
        ALTO_XML_QUEUE_URL: ${construct:alto-xml.queueUrl}
  thumbnail:
    type: queue
    maxRetries: 2
    batchSize: 1
    worker:
      handler: handler.thumbnail
      memorySize: 4096 # optional, in MB, default is 1024
      timeout: 900 # optional, in seconds, default is 6
      ephemeralStorageSize: 2560
      environment:
        RUBYOPT: '-W0'
  word-coordinates:
    type: queue
    maxRetries: 2
    batchSize: 1
    worker:
      handler: handler.word_coordinates
      memorySize: 4096 # optional, in MB, default is 1024
      timeout: 900 # optional, in seconds, default is 6
      ephemeralStorageSize: 2560
      environment:
        RUBYOPT: '-W0'
  plain-text:
    type: queue
    maxRetries: 2
    batchSize: 1
    worker:
      handler: handler.plain_text
      memorySize: 4096 # optional, in MB, default is 1024
      timeout: 900 # optional, in seconds, default is 6
      ephemeralStorageSize: 2560
      environment:
        RUBYOPT: '-W0'
  alto-xml:
    type: queue
    maxRetries: 2
    batchSize: 1
    worker:
      handler: handler.alto_xml
      memorySize: 4096 # optional, in MB, default is 1024
      timeout: 900 # optional, in seconds, default is 6
      ephemeralStorageSize: 2560
      environment:
        RUBYOPT: '-W0'

plugins:
  - serverless-lift
  - ./../serverless-ruby-layer
  - serverless-ignore
custom:
  rubyLayer:
    include_functions:
      - copy
      - split-ocr-thumbnailWorker
      - ocrWorker
      - thumbnailWorker
      - word-coordinatesWorker
      - plain-textWorker
      - alto-xmlWorker
    use_docker: true
    docker_file: Dockerfile
    docker_image_name: ghcr.io/scientist-softserv/space_stone/awsrubylayer:latest
    native_bins:
      - /opt/bin/
    native_libs:
      - /opt/lib/
